project_name: OliveTin
version: 2
before:
  hooks:
    - make service-prep

builds:
  - env:
      - CGO_ENABLED=0
    binary: OliveTin
    main: main.go
    dir: service
    goos:
      - linux

    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{ .CommitDate }}

archives:
  - formats: tar.gz
    files:
      - config.yaml
      - LICENSE
      - README.md
      - Dockerfile
      - webui
      - ./var/
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ .Arm }}"
    wrap_in_directory: true

release:
  footer: |
    ## Upgrade warnings, or breaking changes

    - No such issues between the last release and this version.

    ## Useful links

    - [Which download do I need?](https://docs.olivetin.app/install/choose_package.html)
    - [Ask for help and chat with others users in the Discord community](https://discord.gg/jhYWWpNJ3v)

    Thanks for your interest in OliveTin!
